set(ENABLE_rdServer          ON CACHE BOOL "" FORCE)
set(ENABLE_robotDevastation  ON CACHE BOOL "" FORCE)
set(ENABLE_tests            OFF CACHE BOOL "" FORCE)
set(GENERATE_doc_html        ON CACHE BOOL "" FORCE)

if(WIN32)
    set(CPACK_BINARY_7Z   OFF CACHE BOOL "" FORCE)
    set(CPACK_BINARY_IFW  OFF CACHE BOOL "" FORCE)
    set(CPACK_BINARY_NSIS  ON CACHE BOOL "" FORCE)
    set(CPACK_BINARY_WIX  OFF CACHE BOOL "" FORCE)
    set(CPACK_BINARY_ZIP   ON CACHE BOOL "" FORCE)
endif()

if(UNIX)
    set(CPACK_BINARY_DEB   ON CACHE BOOL "" FORCE)
    set(CPACK_BINARY_IFW  OFF CACHE BOOL "" FORCE)
    set(CPACK_BINARY_NSIS OFF CACHE BOOL "" FORCE)
    set(CPACK_BINARY_RPM  OFF CACHE BOOL "" FORCE)
    set(CPACK_BINARY_STGZ OFF CACHE BOOL "" FORCE)
    set(CPACK_BINARY_TBZ2 OFF CACHE BOOL "" FORCE)
    set(CPACK_BINARY_TGZ   ON CACHE BOOL "" FORCE)
    set(CPACK_BINARY_TXZ  OFF CACHE BOOL "" FORCE)
    set(CPACK_BINARY_TZ   OFF CACHE BOOL "" FORCE)
endif()

set(_version_regex_pattern "^v")

if("True" STREQUAL "$ENV{APPVEYOR}")
    if("true" STREQUAL "$ENV{APPVEYOR_REPO_TAG}")
        string(REGEX REPLACE ${_version_regex_pattern} "" _tagged_version "$ENV{APPVEYOR_REPO_TAG_NAME}")
        set(_CPACK_CI_VERSION ${_tagged_version} CACHE STRING "" INTERNAL)
        unset(_tagged_version)
    else()
        set(_CPACK_CI_VERSION "$ENV{APPVEYOR_BUILD_VERSION}" CACHE INTERNAL "")
    endif()
endif()

if("true" STREQUAL "$ENV{TRAVIS}")
    if(NOT "" STREQUAL "$ENV{TRAVIS_TAG}")
        string(REGEX REPLACE ${_version_regex_pattern} "" _tagged_version "$ENV{TRAVIS_TAG}")
        set(_CPACK_CI_VERSION ${_tagged_version} CACHE STRING "" INTERNAL)
        unset(_tagged_version)
    else()
        set(_CPACK_CI_VERSION "travis.$ENV{TRAVIS_BUILD_NUMBER}" CACHE INTERNAL "")
    endif()
endif()

if(WIN32)
    set(BUNDLE_DEPS ON CACHE BOOL "" FORCE)
endif()

unset(_version_regex_pattern)
